### ISSUE TITLE
missing/assumed install instructions

### ISSUE THREAD

**Issue by walidshaari** [chanwit/flamingo#1]
Great work. much appreciated.
- There is an assumption that argocd is already installed in the namespace argocd
   - if not installed; maybe point them to https://argo-cd.readthedocs.io/en/stable/getting_started/
- The bootstrap heredoc points to your github repo

**Comment by chanwit** [comment]
Thank you very much Walid.

ArgoCD is actually installed by this file: https://github.com/chanwit/flamingo/blob/main/demo/artifacts/fsa-installation/kustomization.yaml

And before that the ArgoCD namespace is created by this file: https://github.com/chanwit/flamingo/blob/main/demo/features/fsa-installation/ks.yaml

what the error message you got please?

**Comment by walidshaari** [comment]
ok, let me recheck

**Comment by walidshaari** [comment]
ok, so I did get these errors after submitting the heredoc
```
unable to recognize "STDIN": no matches for kind "GitRepository" in version "source.toolkit.fluxcd.io/v1beta1"
unable to recognize "STDIN": no matches for kind "Kustomization" in version "kustomize.toolkit.fluxcd.io/v1beta2"

```

so I thought i need to bootstrap flux as per site, I did the following before running the heredoc

```
flux bootstrap git   --url=https://github.com/walidshaari/flamingo   --username=walidshaari   --password=${GITHUB_USER_TOKEN}   --token-auth=true   --path=clusters/kind
```

**Comment by walidshaari** [comment]
You are right, I missed the `flux install` instruction, rerun the steps and it works fine from the first time 👍🏼

**Comment by walidshaari** [comment]
so just in case someone gets the errors:
```
unable to recognize "STDIN": no matches for kind "GitRepository" in version "source.toolkit.fluxcd.io/v1beta1"
unable to recognize "STDIN": no matches for kind "Kustomization" in version "kustomize.toolkit.fluxcd.io/v1beta2"
```

that means they have missed running `flux install` first

**Comment by chanwit** [comment]
yes, that's correct.

**Comment by chanwit** [comment]
I shall close this issue. thank you @walidshaari
